
name: Build CopilotDeskAI Installer
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: {node-version: 18}
      - uses: actions/setup-python@v4
        with: {python-version: "3.10"}
      - name: Install Python deps
        run: |
          pip install -r backend/requirements.txt
          pyinstaller --onefile backend/server.py --name=backend_server
      - name: Install Electron deps
        run: |
          cd app
          npm install
      - name: Build Electron
        run: |
          cd app
          npm run dist
      - name: Upload installer
        uses: softprops/action-gh-release@v1
        with: {files: "app/dist/*.exe"}
        env: {GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"}
